version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - $DB_PORT
    ports:
      - 49153:$DB_PORT
    env_file:
      - .env

  api:
    build: ./api
    container_name: backend
    restart: always
    ports:
      - 3333:5000
      - 5555:5555
    env_file:
      - ./api/.env
    environment:
      NODE_ENV: production
      DB_HOST: dbcontainer
    depends_on:
      - db

  frontend:
    build: ./nextjs-client
    container_name: frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - api
