version: '3.8'

services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    container_name: mysql
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - $DB_PORT
    ports:
      - 49153:$DB_PORT
    env_file:
      - .env

  api:
    build: ./src/backend
    container_name: php_backend
    restart: always
    ports:
      - 8081:80
    env_file:
      - ./.env
    depends_on:
      - db